apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: main-container
    image: main-container-image
  initContainers:
  - name: init-container
    image: init-container-image
