apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  # Uncomment the following section if you are using a specific Storage Class
  # storageClassName: your-storage-class
